### ISSUE TITLE
Slides for all lectures.

### ISSUE THREAD

**Issue by giuseppemag** [hogeschool/INFDEV03-5#1]
2.1 Lecture 0 - Refresher
The course starts with a quick refresher on SQL and RDBMS’s:
Topics • Entities and relationships • SQL operators
2.2 Lecture 2 - indexes
The second lecture covers performance issues in (relational) queries and the potential to use indexes to speed-up execution of such queries:
Topics • Potentially slow query operators: where, join, etc. • Sorting data by value: hash-tables and hashing algorithms • Using a hash-index • Sorting data by value comparison: balanced trees • Using a tree-index
2.3 Lecture 3 - ACID
The third lecture covers the inﬂexible but precise framework of modern ACID (R)DBMS’s:
Topics • Transactions are integral: atomicity • Database maintains valid state: consistency • Transactions are serialized: isolation • Database cannot break: durability
2.4 Lecture 4 - Concurrency
The fourth lecture covers handling of potentially conﬂicting concurrent query execution in an ACID DBMS:
Topics • Serialization • Locks • Deadlocks and their prevention
2.5 Lecture 5 - Crash recovery
The ﬁfth lecture covers handling of disastrous events:
Development 1 28 augustus 2015 4
COURSE DESCRIPTION HOGESCHOOL ROTTERDAM / CMI
Topics • Log • Write-ahead log • Checkpointing • Recovery from a system crash
2.6 Lecture 6 - BASE
The sixth lecture covers an alternative tradeoﬀ to ACID:
Topics • Stay always connected: Basic availability • Acceptance of partially wrong states: Soft state • Slower propagation of updated information: Eventual consistency
2.7 Lecture 7 - Graph databases
The seventh lecture covers a speciﬁc example of no-SQL databases, speciﬁcally graph databases:
Topics • Directed vs undirected graphs • Adjacency list vs matrix • Algorithms on graphs • Case study: Neo4J

**Comment by a-omar** [comment]
Done!
