### ISSUE TITLE
Redundancy example in Lecture 1.pdf

### ISSUE THREAD

**Issue by jeroen-meijer** [hogeschool/INFDEV03-5#9]
In Lecture 1.pdf, on the 6th page, the slide talks about redundancy in columns DNAME and DMGRSSN, but I've noticed that DNUMBER is also redundantly corresponding to DNAME and DMGRSSN.
<img width="796" alt="schermafbeelding 2016-10-11 om 01 00 41" src="https://cloud.githubusercontent.com/assets/14292245/19253941/0c6b680e-8f4f-11e6-82a3-4ca9642fb37a.png">

Greetings.

**Comment by a-omar** [comment]
We emphasised here just one example for the redundancy. But department name can also be considered redundant, since it's number is redundant.
